### ISSUE TITLE
DARTS База: добавление тега игры

### ISSUE THREAD

**Issue by rebelucho** [rebelucho/online-scores#2]
Добавить tag игры
Tag игры, чемпионата, серии игр для формирования ссылки на просмотр игр объединенных по какому-то признаку. Можно будет выбрать все игры с текущим тэгом. Например все игры турнира "Дальневосточного Федерального Округа" по тэгу #ДФО, или кубка города Благовещенска по тегу #kubokblg . Тэг должен быть регистронезависимым.

**Comment by Whiteb2801** [comment]
Тег добавлен в калькулятор и в JSON
