### ISSUE TITLE
DARTS База: флаг окончание игры

### ISSUE THREAD

**Issue by rebelucho** [rebelucho/online-scores#4]
Необходимо добавить флаг окончания игры в выгружаемый файл по окончанию игры. 
`{"gameData" : {"gameEnd": 0, }}`

При наличии этого флага, на фронтэнде отображается расширенная статистика, немного измененный интерфейс, убирается автообновление результатов, запрещается обновление результатов игры.

**Comment by Whiteb2801** [comment]
Добавил параметр gameEnd, который принимает  значения Истина/Ложь
